apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: logan
  namespace: logan
spec:
  rules:
    - host: logan.example.com
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: logan-api
                port:
                  number: 8000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: logan-web
                port:
                  number: 3000
