apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: logan-default
  namespace: logan
spec:
  podSelector: {}
  policyTypes: ["Ingress", "Egress"]
  ingress:
    - from:
        - namespaceSelector: {}
  egress:
    - to:
        - namespaceSelector: {}
